# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo build step
      - run: mkdir build-output
      - run: touch build-output/artifact.txt
      - persist_to_workspace:
          root: build-output
          paths:
            - '*'
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo test step
      - attach_workspace:
          at: ~/repo/workspace
      - run: ls ~/repo/workspace/artifact.txt

  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo deploy step
      - run: ls ~/repo/workspace/artifact.txt

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
           