# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build-frontend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo build-frontend step
  
  build-backend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo build-backend step

  test-frontend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo test-frontend step
  
  test-backend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo test-backend step

  integration-tests:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo integration-tests step

  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo deploy step

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires:
            - build-backend
      - integration-tests:
          requires:
            - build-frontend
            - build-backend
      - deploy:
          requires:
            - test-frontend
            - test-backend
            - integration-tests 